<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UseTestingPlatform>true</UseTestingPlatform>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="1.69.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Libs\TelegramBot\Seedysoft.Libs.TelegramBot.csproj" />
        <ProjectReference Include="..\Infrastructure.Tests\Seedysoft.Libs.Infrastructure.Tests.csproj" />
    </ItemGroup>
</Project>
