<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UseTestingPlatform>true</UseTestingPlatform>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="1.65.68" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Libs\Core\Seedysoft.Libs.Core.csproj" />
        <ProjectReference Include="..\..\..\src\Libs\Cryptography\Seedysoft.Libs.Cryptography.csproj" />
        <ProjectReference Include="..\Core.Tests\Seedysoft.Libs.Core.Tests.csproj" />
    </ItemGroup>
</Project>