// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seedysoft.Libs.Infrastructure.DbContexts;

#nullable disable

namespace Seedysoft.Libs.Infrastructure.Migrations.DbRpt
{
    [DbContext(typeof(Infrastructure.DbContexts.DbRpt))]
    partial class DbRptModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.CentroDirectivo", b =>
                {
                    b.Property<int>("CentroDirectivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CentroDirectivoDenominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinisterioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CentroDirectivoId");

                    b.HasIndex("MinisterioId");

                    b.ToTable("CentroDirectivo", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Localidad", b =>
                {
                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalidadDenominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaisId", "ProvinciaId", "LocalidadId");

                    b.ToTable("Localidad", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Ministerio", b =>
                {
                    b.Property<int>("MinisterioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MinisterioDenominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MinisterioId");

                    b.ToTable("Ministerio", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaisDenominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaisId");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Provincia", b =>
                {
                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProvinciaDenominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PaisId", "ProvinciaId");

                    b.ToTable("Provincia", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Puesto", b =>
                {
                    b.Property<int>("PuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adscripcion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ComplementoEspecifico")
                        .HasPrecision(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormacionEspecifica")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrupoSubgrupo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProvinciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provision")
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoDenominacionCorta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoDenominacionLarga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitulacionAcademica")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PuestoId");

                    b.HasIndex("UnidadId");

                    b.HasIndex("PaisId", "ProvinciaId", "LocalidadId");

                    b.ToTable("Puesto", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Unidad", b =>
                {
                    b.Property<int>("UnidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentroDirectivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnidadDenominacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UnidadId");

                    b.HasIndex("CentroDirectivoId");

                    b.HasIndex("PaisId", "ProvinciaId", "LocalidadId");

                    b.ToTable("Unidad", (string)null);
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.CentroDirectivo", b =>
                {
                    b.HasOne("Seedysoft.Libs.Core.Entities.Ministerio", "Ministerio")
                        .WithMany()
                        .HasForeignKey("MinisterioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CentroDirectivo_MinisterioId");

                    b.Navigation("Ministerio");
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Localidad", b =>
                {
                    b.HasOne("Seedysoft.Libs.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_PaisId");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("PaisId", "ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Localidad_Provincia");

                    b.Navigation("Pais");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Provincia", b =>
                {
                    b.HasOne("Seedysoft.Libs.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Provincia_PaisId");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Puesto", b =>
                {
                    b.HasOne("Seedysoft.Libs.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Puesto_PaisId");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("UnidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Puesto_UnidadId");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("PaisId", "ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Puesto_Provincia");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("PaisId", "ProvinciaId", "LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Puesto_Localidad");

                    b.Navigation("Localidad");

                    b.Navigation("Pais");

                    b.Navigation("Provincia");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("Seedysoft.Libs.Core.Entities.Unidad", b =>
                {
                    b.HasOne("Seedysoft.Libs.Core.Entities.CentroDirectivo", "CentroDirectivo")
                        .WithMany()
                        .HasForeignKey("CentroDirectivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Unidad_CentroDirectivoId");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Puesto_PaisId");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("PaisId", "ProvinciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Puesto_Provincia");

                    b.HasOne("Seedysoft.Libs.Core.Entities.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("PaisId", "ProvinciaId", "LocalidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Unidad_Localidad");

                    b.Navigation("CentroDirectivo");

                    b.Navigation("Localidad");

                    b.Navigation("Pais");

                    b.Navigation("Provincia");
                });
#pragma warning restore 612, 618
        }
    }
}
