<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <UseTestingPlatform>true</UseTestingPlatform>
    </PropertyGroup>
    <ItemGroup>
      <Compile Include="..\..\TUnitTestClassBase.cs" Link="TUnitTestClassBase.cs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
        <PackageReference Include="TUnit" Version="1.69.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\Libs\Core\Seedysoft.Libs.Core.csproj" />
    </ItemGroup>
</Project>