<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPublishable>False</IsPublishable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Seedysoft.Libs.Cryptography.Tests" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    </ItemGroup>
</Project>
