<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\Usings.cs" Link="Usings.cs" />
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
        <PackageReference Include="OneOf" Version="3.0.271" />
        <PackageReference Include="OneOf.Serialization.SystemTextJson" Version="1.1.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Seedysoft.Libs.Core.csproj" />
        <ProjectReference Include="..\GasStationPrices\Seedysoft.Libs.GasStationPrices.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\css\images\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="libman.json">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
</Project>
