<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\..\Usings.cs" Link="Usings.cs" />
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
        <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.114" />
        <PackageReference Include="OneOf" Version="3.0.271" />
        <PackageReference Include="OneOf.Serialization.SystemTextJson" Version="1.1.1" />
        <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Seedysoft.Libs.Core.csproj" />
        <ProjectReference Include="..\GasStationPrices\Seedysoft.Libs.GasStationPrices.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="wwwroot\css\images\" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="libman.json" />
        <None Include="libman.json">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>
