# -v  | --verbosity <LEVEL> # Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]. The default is minimal.

name: CI

env:
  SEEDY_MASTER_KEY: ${{ secrets.SEEDY_MASTER_KEY }}

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  pull_request:
  push:
    branches-ignore:
      - 'feat/fix-github-actions'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 8

      - name: Build
        run: dotnet build Seedysoft.Tests.sln -c Release -v n

      - name: Test
        run: dotnet test Seedysoft.Tests.sln -c Release --no-build -v n
