# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        token: ${{ secrets.PAT }}
        submodules: 'recursive'
        
    - name: Setup .NET
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/*.sln
      
    - name: Build
      run: dotnet build src/*.sln --no-restore
      
    - name: Test
      run: dotnet test src/*.sln --no-build --verbosity normal
