# -v  | --verbosity <LEVEL> # Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]. The default is minimal.

name: Publish

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  push:
    tags:
      - '**'
  workflow_dispatch:
  
jobs:

  linux:
    name: Publish on linux
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        runtime: [ 'linux-arm64', 'linux-x64' ]
    steps:
      - uses: actions/checkout@main
      - name: Setup dotnet
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 8
      - name: Build
        run: dotnet build Seedysoft.Tests.sln -c Release --nologo -v m
      - name: Publish
        id: publish-linux
        run: |
          mkdir -p "./pub/${{ matrix.runtime }}"
          echo ${{ github.workspace }}
          dotnet publish ./src/BlazorWebApp/Server/Seedysoft.BlazorWebApp.Server.csproj -c Release --nologo --no-restore -o "./pub/${{ matrix.runtime }}" -p:PublishTrimmed=false -r "${{ matrix.runtime }}" --sc -v m
      - name: Pack
        if: steps.publish-linux.outcome == 'success'
        run: |
          echo ${{ github.workspace }}
          tar czf "${{ github.workspace }}/pub/${{ matrix.runtime }}.${{ github.ref_name }}.tar.gz" "./pub/${{ matrix.runtime }}"

  # windows:
  #   name: Publish on windows
  #   runs-on: [ windows-latest ]
  #   strategy:
  #     matrix:
  #       runtime: [ 'win-x64' ]
  #   steps:
  #     - uses: actions/checkout@main
  #     - name: Setup dotnet
  #       uses: actions/setup-dotnet@main
  #       with:
  #         dotnet-version: 8
  #     - name: Build
  #       run: dotnet build Seedysoft.Tests.sln -c Release --nologo -v m
  #     - name: Publish
  #       id: publish-windows
  #       run: |
  #         mkdir -p "./pub/${{ matrix.runtime }}"
  #         dotnet publish ./src/BlazorWebApp/Server/Seedysoft.BlazorWebApp.Server.csproj -c Release --nologo --no-restore -o "./pub/${{ matrix.runtime }}" -p:PublishTrimmed=false -r "${{ matrix.runtime }}" --sc -v m
  #     - name: Pack
  #       if: steps.publish-windows.outcome == 'success'
  #       run: 7z a -r -tzip "./pub/${{ matrix.runtime }}.${{ github.ref_name }}.zip" "./pub/${{ matrix.runtime }}" *

  release:
    name: Create a release
    # needs: [ linux, windows ]
    needs: [ linux ]
    runs-on: [ ubuntu-latest ]
    steps:        
      - name: Make Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          fail_on_unmatched_files: false
          generate_release_notes: true
          files: |
            "./pub/*${{ github.ref_name }}.tar.gz"
            "./pub/*${{ github.ref_name }}.zip"