# -v  | --verbosity <LEVEL> # Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]. The default is minimal.

name: Publish

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  push:
    tags:
      - '**'

jobs:
  publish-and-release:
    name: Publish and release
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 8.0.x

      - name: Publish runtimes
        id: publish-runtimes
        run: |
          # Publish
          dotnet publish ./src/BlazorWebApp/Server/Seedysoft.BlazorWebApp.Server.csproj -c Release -p:PublishTrimmed=false --sc -v n
          # Pack files
          tar czvf "${{ github.ref_name }}.tar.gz" "./src/BlazorWebApp/Server/bin/Release/net8.0/linux-x64/publish/"
          # 7z a -tzip "${{ github.ref_name }}.zip" "./src/BlazorWebApp/Server/bin/Release/net8.0/win-x64/publish/*"

      - name: Make Release
        id: make-release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          fail_on_unmatched_files: false
          generate_release_notes: true
          files: |
            ${{ github.ref_name }}.tar.gz
            ${{ github.ref_name }}.zip
