# -v  | --verbosity <LEVEL> # Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]. The default is minimal.

name: Publish

concurrency:
  cancel-in-progress: true
  group: '**'

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  obtain_version:
    name: Obtain version
    outputs:
      tag_version: ${{ steps.get-version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
    - name: Get Version
      id: get-version
      run: |
        echo "version=$(date -u +%y.%m%d.%H%M)" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
    - name: Checkout Repository
      uses: actions/checkout@main
    - name: Setup dotnet
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8
    - name: Build solution
      run: |
        dotnet workload install wasm-tools
        dotnet build Seedysoft.Tests.sln -c Release -v n

  publish_and_pack_job:
    name: Publish and pack
    needs: obtain_version
    runs-on: ${{ matrix.runtime.os }}
    strategy:
      fail-fast: true
      matrix:
        runtime:
        - { name: linux-arm64, os: ubuntu-latest  }
        - { name: linux-x64,   os: ubuntu-latest  }
        - { name: win-x64,     os: windows-latest }
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
    - name: Setup dotnet
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 8
    - name: Make publish folder "./${{ matrix.runtime.name }}/"
      run: mkdir -p "./${{ matrix.runtime.name }}/"
    - name: Install wasm-tools workload
      run: dotnet workload install wasm-tools
    - name: Publish Outbox
      run: dotnet publish "./src/Outbox/ConsoleApp/Seedysoft.Outbox.ConsoleApp.csproj" -o "./${{ matrix.runtime.name }}/" -p:AssemblyVersion="${{ needs.obtain_version.outputs.tag_version }}" -r "${{ matrix.runtime.name }}" -c Release --nologo -p:PublishTrimmed=false --sc -v m
    - name: Build Pvpc
      run: dotnet publish "./src/Pvpc/ConsoleApp/Seedysoft.Pvpc.ConsoleApp.csproj" -o "./${{ matrix.runtime.name }}/" -p:AssemblyVersion="${{ needs.obtain_version.outputs.tag_version }}" -r "${{ matrix.runtime.name }}" -c Release --nologo -p:PublishTrimmed=false --sc -v m
    - name: Publish Update
      run: dotnet publish "./src/Update/ConsoleApp/Seedysoft.Update.ConsoleApp.csproj" -o "./${{ matrix.runtime.name }}/" -p:AssemblyVersion="${{ needs.obtain_version.outputs.tag_version }}" -r "${{ matrix.runtime.name }}" -c Release --nologo -p:PublishTrimmed=false --sc -v m
    - name: Publish WebComparer
      run: dotnet publish "./src/WebComparer/ConsoleApp/Seedysoft.WebComparer.ConsoleApp.csproj" -o "./${{ matrix.runtime.name }}/" -p:AssemblyVersion="${{ needs.obtain_version.outputs.tag_version }}" -r "${{ matrix.runtime.name }}" -c Release --nologo -p:PublishTrimmed=false --sc -v m
    - name: Publish BlazorWebApp
      run: dotnet publish "./src/BlazorWebApp/Server/Seedysoft.BlazorWebApp.Server.csproj" -o "./${{ matrix.runtime.name }}/" -p:AssemblyVersion="${{ needs.obtain_version.outputs.tag_version }}" -r "${{ matrix.runtime.name }}" -c Release --nologo -p:PublishTrimmed=false --sc -v m
    - name: Pack to ${{ matrix.runtime.name }}.${{ needs.obtain_version.outputs.tag_version }}.7z
      id: pack
      run: |
        cd ${{ matrix.runtime.name }}/
        7z a -r -t7z "../${{ matrix.runtime.name }}.${{ needs.obtain_version.outputs.tag_version }}.7z" *
        cd ..
    - name: Upload artifact ${{ matrix.runtime.name }}.${{ needs.obtain_version.outputs.tag_version }}.7z
      if: steps.pack.outcome == 'success'
      uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.runtime.name }}.${{ needs.obtain_version.outputs.tag_version }}.7z
        path: "${{ matrix.runtime.name }}.${{ needs.obtain_version.outputs.tag_version }}.7z"
        compression-level: 0
        if-no-files-found: error # `warn` or `ignore` are also available, defaults to `warn`
          
  release_job:
    name: Create a release
    needs: 
    - obtain_version
    - publish_and_pack_job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@main
    - name: Make download folder
      run: mkdir -p ./artifacts/
    - name: Download published app as artifact
      uses: actions/download-artifact@main
      with:
        path: ./artifacts
    - name: Create a tag
      run: |
        git tag ${{ needs.obtain_version.outputs.tag_version }}
        git push origin ${{ needs.obtain_version.outputs.tag_version }}
    - name: Make Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ needs.obtain_version.outputs.tag_version }}
        fail_on_unmatched_files: true
        files: ./artifacts/*/*.7z
        generate_release_notes: true
        tag_name: ${{ needs.obtain_version.outputs.tag_version }}
